import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { BoardIncident, TimelineEntry } from './types'
import { dateShort, stamp } from './format'

const BRAND = { ink: '#333333', teal: '#25BEC8', faint: '#8a8a8a' }

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

function csvCell(value: unknown): string {
  if (value === null || value === undefined) return ''
  const s = String(value)
  // Guard against spreadsheet formula injection in exported audit evidence.
  const safe = /^[=+\-@\t\r]/.test(s) ? `'${s}` : s
  return /[",\n\r]/.test(safe) ? `"${safe.replace(/"/g, '""')}"` : safe
}

export interface ExportContext {
  incidents: BoardIncident[]
  timelines?: Record<string, TimelineEntry[]>
  filterSummary: string
  generatedBy: string
  generatedRole: string
}

const COLUMNS: Array<[string, (i: BoardIncident) => unknown]> = [
  ['Reference', (i) => i.ref],
  ['Event', (i) => i.event_name],
  ['Client', (i) => i.event_client],
  ['Raised (date)', (i) => dateShort(i.created_at)],
  ['Raised (time)', (i) => new Date(i.created_at).toISOString()],
  ['Category', (i) => i.category],
  ['Severity', (i) => i.severity],
  ['Status', (i) => i.status],
  ['Location / zone', (i) => i.location],
  ['Command level', (i) => i.command_level],
  ['Reported by', (i) => (i.restricted ? 'RESTRICTED — medical' : (i.reported_by ?? ''))],
  ['Logged by', (i) => i.created_by_name ?? ''],
  ['Description', (i) => (i.restricted ? 'RESTRICTED — medical' : (i.description ?? ''))],
  ['Resources deployed', (i) => (i.restricted ? 'RESTRICTED — medical' : (i.resources_deployed ?? ''))],
  ['Outcome', (i) => (i.restricted ? 'RESTRICTED — medical' : (i.outcome ?? ''))],
  ['Closed by', (i) => i.closed_by_name ?? ''],
  ['Closed at', (i) => (i.closed_at ? new Date(i.closed_at).toISOString() : '')],
  ['Follow-up required', (i) => (i.follow_up_required ? 'Yes' : 'No')],
]

export function exportCsv(ctx: ExportContext) {
  const lines: string[] = []

  lines.push(csvCell('Tide Events Group Scotland — Incident Export'))
  lines.push([csvCell('Generated'), csvCell(stamp(new Date()))].join(','))
  lines.push(
    [csvCell('Generated by'), csvCell(`${ctx.generatedBy} (${ctx.generatedRole})`)].join(','),
  )
  lines.push([csvCell('Filter'), csvCell(ctx.filterSummary)].join(','))
  lines.push([csvCell('Records'), csvCell(ctx.incidents.length)].join(','))
  lines.push('')

  lines.push(COLUMNS.map(([header]) => csvCell(header)).join(','))
  for (const incident of ctx.incidents) {
    lines.push(COLUMNS.map(([, get]) => csvCell(get(incident))).join(','))
  }

  if (ctx.timelines) {
    lines.push('')
    lines.push(csvCell('TIMELINE ENTRIES'))
    lines.push(
      ['Reference', 'At', 'Author', 'Role', 'Entry type', 'Entry'].map(csvCell).join(','),
    )
    for (const incident of ctx.incidents) {
      for (const entry of ctx.timelines[incident.id] ?? []) {
        lines.push(
          [
            incident.ref,
            new Date(entry.at).toISOString(),
            entry.author_name,
            entry.author_role ?? '',
            entry.entry_type,
            entry.body,
          ]
            .map(csvCell)
            .join(','),
        )
      }
    }
  }

  download(
    new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' }),
    `tide-incidents-${new Date().toISOString().slice(0, 10)}.csv`,
  )
}

export function exportPdf(ctx: ExportContext) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' })
  const width = doc.internal.pageSize.getWidth()

  doc.setFillColor(BRAND.ink)
  doc.rect(0, 0, width, 56, 'F')
  doc.setTextColor('#FFFFFF')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('Incident Management System', 40, 26)
  doc.setTextColor(BRAND.teal)
  doc.setFontSize(9)
  doc.text('TIDE EVENTS GROUP SCOTLAND — AUDIT EXPORT', 40, 42)

  doc.setTextColor(BRAND.ink)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(`Generated: ${stamp(new Date())}`, 40, 78)
  doc.text(`Generated by: ${ctx.generatedBy} (${ctx.generatedRole})`, 40, 92)
  doc.text(`Records: ${ctx.incidents.length}`, 40, 106)
  doc.text(doc.splitTextToSize(`Filter: ${ctx.filterSummary}`, width - 340), 340, 78)

  autoTable(doc, {
    startY: 124,
    head: [
      ['Ref', 'Date', 'Event', 'Category', 'Severity', 'Zone', 'Command', 'Status', 'Detail'],
    ],
    body: ctx.incidents.map((i) => [
      i.ref,
      dateShort(i.created_at),
      i.event_name,
      i.category,
      i.severity,
      i.location,
      i.command_level,
      i.status,
      i.restricted ? 'RESTRICTED — medical detail withheld' : (i.description ?? ''),
    ]),
    styles: { font: 'helvetica', fontSize: 7.5, cellPadding: 4, textColor: BRAND.ink },
    headStyles: { fillColor: BRAND.ink, textColor: '#FFFFFF', fontSize: 7.5 },
    alternateRowStyles: { fillColor: '#FAF6F4' },
    columnStyles: { 8: { cellWidth: 190 } },
    margin: { left: 40, right: 40 },
  })

  if (ctx.timelines) {
    for (const incident of ctx.incidents) {
      const entries = ctx.timelines[incident.id] ?? []
      if (entries.length === 0) continue

      doc.addPage()
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(11)
      doc.setTextColor(BRAND.ink)
      doc.text(`${incident.ref} — ${incident.category}, ${incident.location}`, 40, 46)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8.5)
      doc.setTextColor(BRAND.faint)
      doc.text(
        `${incident.event_name} · ${incident.severity} · ${incident.status} · ${incident.command_level}`,
        40,
        62,
      )

      autoTable(doc, {
        startY: 78,
        head: [['Time', 'Author', 'Role', 'Type', 'Entry']],
        body: entries.map((e) => [
          stamp(e.at),
          e.author_name,
          e.author_role ?? '',
          e.entry_type,
          e.body,
        ]),
        styles: { font: 'helvetica', fontSize: 8, cellPadding: 4, textColor: BRAND.ink },
        headStyles: { fillColor: BRAND.teal, textColor: '#FFFFFF', fontSize: 8 },
        columnStyles: { 4: { cellWidth: 380 } },
        margin: { left: 40, right: 40 },
      })
    }
  }

  const pages = doc.getNumberOfPages()
  for (let p = 1; p <= pages; p += 1) {
    doc.setPage(p)
    doc.setFontSize(7.5)
    doc.setTextColor(BRAND.faint)
    doc.text(
      'Confidential — audit evidence. Medical detail is withheld where role restrictions apply.',
      40,
      doc.internal.pageSize.getHeight() - 20,
    )
    doc.text(
      `Page ${p} of ${pages}`,
      width - 40,
      doc.internal.pageSize.getHeight() - 20,
      { align: 'right' },
    )
  }

  doc.save(`tide-incident-report-${new Date().toISOString().slice(0, 10)}.pdf`)
}
